services:
  run-server:
    image: ghcr.io/watsona4/testmynet:latest
    build: .
    restart: unless-stopped
    volumes:
      - .:/root/run-server/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
