FROM ubuntu:latest

WORKDIR /app

RUN apt-get update && apt-get install -y curl tzdata

ENV TZ="America/New_York"
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN dpkg-reconfigure tzdata

RUN curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash

RUN apt-get install -y \
    speedtest-cli \
    python3-yaml \
    python3-paho-mqtt

COPY run_server.py .

CMD ["python3", "run_server.py"]